# ------------------- General Options -------------------------

description                  : AgentFormer (Before DLow)
results_root_dir             : results
seed                         : 1
dataset                      : nba

# ------------------- Feature Extractor -------------------------

past_frames                  : 5
future_frames                : 10
min_past_frames              : 5
min_future_frames            : 10

traj_scale                   : 1
motion_dim                   : 2
forecast_dim                 : 2

# ------------------- Model -------------------------

model_id: agentformer
tf_version: v2
tf_model_dim: 256
tf_ff_dim: 512
tf_nhead: 8
tf_dropout: 0.1
input_type: ['scene_norm', 'vel']
pred_type: 'scene_norm'
sn_out_type: 'norm'
pos_concat: true

context_encoder:
  nlayer: 2

future_decoder:
  nlayer: 2
  out_mlp_dim: [512, 256]

future_encoder:
  nlayer: 2
  out_mlp_dim: [512, 256]

# ------------------- VAE-------------------------

nz                           : 32
sample_k                     : 20
learn_prior                  : false

# ------------------- Training Parameters -------------------------

lr                           : 1.e-4
loss_cfg:
  mse:
    weight: 1.0
  kld:
    weight: 1.0
    min_clip: 2.0
  sample:
    weight: 1.0
    k: 20
  recover:
    weight: 1.0

batch_size: 32
num_epochs                   : 100
lr_fix_epochs                : 10
lr_scheduler: 'step'
decay_step: 10
decay_gamma: 0.5
print_freq                   : 100
model_save_freq              : 5

